FROM node:20-alpine AS base

FROM base AS installer
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
WORKDIR /app/kafka_consumer_2
COPY ./kafka_consumer_2/package*.json ./
COPY ./kafka_consumer_2 ./
RUN npm install
RUN npx prisma generate
RUN npm prune --production

FROM base AS builder 
WORKDIR /app/kafka_consumer_2
COPY --from=installer /app/kafka_consumer_2  ./
RUN npm run build

FROM base as runner
WORKDIR /appkafka_consumer_2
COPY --from=builder /app/kafka_consumer_2  ./
CMD ["node","run","start"]
