FROM node:20-alpine AS base

FROM base AS installer
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
WORKDIR /app
COPY ./package*.json .
COPY . .
RUN npm install
RUN npx prisma generate
RUN npm prune --production

FROM base AS builder 
WORKDIR /app
COPY --from=installer /app  ./
RUN npm run build

FROM base as runner
WORKDIR /app
COPY --from=builder /app  ./
CMD ["node","run","start"]
