FROM node:20-alpine AS base

FROM base AS installer
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
WORKDIR /app
COPY ./package*.json .
COPY . .
RUN npm install --prod
RUN npx prisma generate

FROM base AS builder 
WORKDIR /app
COPY --from=installer /app  ./
RUN npm run build

CMD ["node","run","start"]
