FROM node:20-alpine as base

FROM base as intaller
WORKDIR /app
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
COPY ./package*.json .
RUN npm install --include=dev
COPY . .
RUN npx prisma generate

FROM base as builder 
ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_FRONTEND_URL
ENV NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
ENV NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
WORKDIR /app
COPY --from=installer /app ./
RUN npm run build

FROM base as runner
WORKDIR /app
COPY --from=builder  /app ./

CMD ["node","server.js"]
