FROM python:3.11-slim
WORKDIR app/reach-backend
COPY ./reach-backend/requirements.txt ./
RUN python -m venv venv \
    && venv/bin/pip install --upgrade pip \
    && venv/bin/pip install --no-cache-dir -r requirements.txt
COPY ./reach-backend ./ 
EXPOSE 8000
CMD ["/app/reach-backend/venv/bin/uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]