"""Add new fields to user model

Revision ID: 41fee07a10ff
Revises: 
Create Date: 2025-07-18 13:28:43.384749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41fee07a10ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_GroupMessages_id'), table_name='GroupMessages')
    op.drop_table('GroupMessages')
    op.drop_index(op.f('ix_UserMessages_id'), table_name='UserMessages')
    op.drop_table('UserMessages')
    op.drop_index(op.f('ix_IndividualMessage_id'), table_name='IndividualMessage')
    op.drop_table('IndividualMessage')
    op.drop_index(op.f('ix_UserFeedBack_id'), table_name='UserFeedBack')
    op.drop_index(op.f('ix_UserFeedBack_projectId'), table_name='UserFeedBack')
    op.drop_table('UserFeedBack')
    op.drop_index(op.f('ix_IndividualMessageStatus_id'), table_name='IndividualMessageStatus')
    op.drop_index(op.f('ix_IndividualMessageStatus_messageId'), table_name='IndividualMessageStatus')
    op.drop_index(op.f('ix_IndividualMessageStatus_receiverId'), table_name='IndividualMessageStatus')
    op.drop_table('IndividualMessageStatus')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_managerFeedBack_id'), table_name='managerFeedBack')
    op.drop_table('managerFeedBack')
    op.drop_table('roles')
    op.drop_index(op.f('ix_Projects_id'), table_name='Projects')
    op.drop_table('Projects')
    op.drop_index(op.f('ix_users_emailId'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ProjectMembers_id'), table_name='ProjectMembers')
    op.drop_table('ProjectMembers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProjectMembers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phoneNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['Projects.id'], name=op.f('ProjectMembers_projectId_fkey')),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('ProjectMembers_userId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ProjectMembers_pkey'))
    )
    op.create_index(op.f('ix_ProjectMembers_id'), 'ProjectMembers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobileNumber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emailId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_emailId'), 'users', ['emailId'], unique=True)
    op.create_table('Projects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Projects_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('projectName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('managerName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('managerId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projectDiscription', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('projectStatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('projectStartDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('projectEndDate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('isFeedBackeOpen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['managerId'], ['users.id'], name='Projects_managerId_fkey'),
    sa.PrimaryKeyConstraint('id', name='Projects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_Projects_id'), 'Projects', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('managerFeedBack',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_delivery', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiverId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('work_accuracy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_collaboration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('areas_for_improvement', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeStamp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['Projects.id'], name=op.f('managerFeedBack_projectId_fkey')),
    sa.ForeignKeyConstraint(['receiverId'], ['users.id'], name=op.f('managerFeedBack_receiverId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('managerFeedBack_pkey'))
    )
    op.create_index(op.f('ix_managerFeedBack_id'), 'managerFeedBack', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_roles_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roles_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('user_roles_pkey'))
    )
    op.create_table('IndividualMessageStatus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('messageId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiverId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isMessageSeen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isReceived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isDelevered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('timeStamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['messageId'], ['IndividualMessage.id'], name=op.f('IndividualMessageStatus_messageId_fkey')),
    sa.ForeignKeyConstraint(['receiverId'], ['users.id'], name=op.f('IndividualMessageStatus_receiverId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('IndividualMessageStatus_pkey'))
    )
    op.create_index(op.f('ix_IndividualMessageStatus_receiverId'), 'IndividualMessageStatus', ['receiverId'], unique=False)
    op.create_index(op.f('ix_IndividualMessageStatus_messageId'), 'IndividualMessageStatus', ['messageId'], unique=False)
    op.create_index(op.f('ix_IndividualMessageStatus_id'), 'IndividualMessageStatus', ['id'], unique=False)
    op.create_table('UserFeedBack',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('senderId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeStamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['Projects.id'], name=op.f('UserFeedBack_projectId_fkey')),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], name=op.f('UserFeedBack_senderId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('UserFeedBack_pkey'))
    )
    op.create_index(op.f('ix_UserFeedBack_projectId'), 'UserFeedBack', ['projectId'], unique=False)
    op.create_index(op.f('ix_UserFeedBack_id'), 'UserFeedBack', ['id'], unique=False)
    op.create_table('IndividualMessage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('senderId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timeStamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['Projects.id'], name=op.f('IndividualMessage_projectId_fkey')),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], name=op.f('IndividualMessage_senderId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('IndividualMessage_pkey'))
    )
    op.create_index(op.f('ix_IndividualMessage_id'), 'IndividualMessage', ['id'], unique=False)
    op.create_table('UserMessages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('messageId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiverId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeStamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('isSeen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['Projects.id'], name=op.f('UserMessages_projectId_fkey')),
    sa.ForeignKeyConstraint(['receiverId'], ['users.id'], name=op.f('UserMessages_receiverId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('UserMessages_pkey'))
    )
    op.create_index(op.f('ix_UserMessages_id'), 'UserMessages', ['id'], unique=False)
    op.create_table('GroupMessages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fileLink', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('senderId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeStamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['Projects.id'], name=op.f('GroupMessages_projectId_fkey')),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], name=op.f('GroupMessages_senderId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('GroupMessages_pkey'))
    )
    op.create_index(op.f('ix_GroupMessages_id'), 'GroupMessages', ['id'], unique=False)
    # ### end Alembic commands ###
