FROM node:20-alpine as base
FROM base AS installer
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
WORKDIR /app
COPY ./package*.json .
COPY . .
RUN npm install --prod
RUN npx prisma generate

FROM base as builder 
WORKDIR /app
COPY --from=installer /app  ./
RUN npm run build


FROM base as runner
WORKDIR /app
COPY --from=builder /app  ./
EXPOSE 8080
CMD ["node","run","start"]