name:
    reach build
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev   
jobs:
  build-and-push:
    environment: staging
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

      - name: Build & Push kafka_consumer_1
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./kafka_consumer_1/Dockerfile.staging
          build-args: |
                DATABASE_URL=${{secrets.DATABASE_URL}}      
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/kafka_consumer1:${{ env.COMMIT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/kafka_consumer1:latest

      - name: Build & Push kafka_consumer_2
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./kafka_consumer_2/Dockerfile.staging
          build-args: |
                DATABASE_URL=${{secrets.DATABASE_URL}}      
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/kafka_consumer2:${{ env.COMMIT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/kafka_consumer2:latest

      - name: Build & Push ws-server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ws-server/Dockerfile.staging
          build-args: |
                DATABASE_URL=${{secrets.DATABASE_URL}}  
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/reach-ws-server:${{ env.COMMIT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/reach-ws-server:latest    

      - name: Build & push reach_backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./reach-backend/Dockerfile.staging
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/reach-backend:${{ env.COMMIT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/reach-backend:latest    
      
      - name: Build & push reach
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./reach-frontend/Dockerfile.staging
          build-args: |
                NEXT_PUBLIC_BACKEND_API_URL=${{secrets.NEXT_PUBLIC_BACKEND_API_URL}}
                NEXT_PUBLIC_FRONTEND_API_URL=${{secrets.NEXT_PUBLIC_FRONTEND_API_URL}}
                NEXT_PUBLIC_WS_SERVER=${{secrets.NEXT_PUBLIC_WS_SERVER}}
                
                DATABASE_URL=${{secrets.DATABASE_URL}}   
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/reach-frontend:${{ env.COMMIT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/reach-frontend:latest    

      
  Deploy:  
    runs-on: ubuntu-latest
    environment: staging
    needs: build-and-push
    env:
        COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install kubeseal
        run: |
            KUBESEAL_VERSION="v0.32.2"
            curl -OL "https://github.com/bitnami-labs/sealed-secrets/releases/download/${KUBESEAL_VERSION}/kubeseal-0.32.2-linux-amd64.tar.gz"
            tar -xvzf kubeseal-0.32.2-linux-amd64.tar.gz kubeseal
            sudo install -m 755 kubeseal /usr/local/bin/kubeseal



      - name: Checkout GitOps repo
        run: |
          mkdir -p ~/gitops
          cd ~/gitops
          sudo apt-get update && sudo apt-get install -y git
          export GITOPS_BRANCH=${{secrets.GITOPS_BRANCH}}
          export GITOPS_REPO=${{secrets.GITOPS_REPO}}
          export TOKEN=${{secrets.TOKEN}}
          export DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}
          git clone --branch $GITOPS_BRANCH https://$TOKEN@github.com/$DOCKER_USERNAME/$GITOPS_REPO.git
        

      - name: Update values.yml and seal secret
        run: |
          cd ~/gitops
          ls
          cd ..
          cd ~/gitops/Helm/chart.prod
          export GITOPS_BRANCH=${{secrets.GITOPS_BRANCH}}
          export GITOPS_REPO=${{secrets.GITOPS_REPO}}
          export GITOPS_BRANCH=${{secrets.GITOPS_BRANCH}}
          git checkout $GITOPS_BRANCH
    
          yq -i ".services.frontend.image = \"reach-frontend:${GITHUB_SHA}\"" values.prod.yml

          yq -i ".services.backend.image = \"reach-backend:${GITHUB_SHA}\"" values.prod.yml

          yq -i ".services.ws-server.image = \"reach-ws-server:${GITHUB_SHA}\"" values.prod.yml

          yq -i ".services.kafka_consumer1.image = \"kafka-consumer1:${GITHUB_SHA}\"" values.prod.yml

          yq -i ".services.kafka_consumer2.image = \"kafka-consumer2:${GITHUB_SHA}\"" values.prod.yml
          
      - name: Setup Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
          kubectl get nodes

      - name: Create and Seal the Secret
        run: |
          ls
          cd ~/gitops/Helm/chart.prod
          export GITOPS_BRANCH=${{secrets.GITOPS_BRANCH}}
          git checkout $GITOPS_BRANCH
          kubeseal --fetch-cert --controller-name sealed-secrets-controller --controller-namespace sealed-secrets > pub-sealed-secrets.pem
          kubectl create secret docker-registry docker-secret \
          --docker-username=${{secrets.DOCKER_USERNAME}} \
          --docker-password=${{secrets.DOCKER_PASSWORD}} \
          --namespace=default \
          --dry-run=client -o yaml

          kubectl create secret generic frontend-secret \
          --from-literal=NEXT_PUBLIC_BACKEND_API_URL=${{secrets.NEXT_PUBLIC_BACKEND_API_URL}} \
          --from-literal=secret_key=${{secrets.SECRET_KEY}} \
          --from-literal=NEXT_PUBLIC_FRONTEND_API_URL=${{secrets.NEXT_PUBLIC_FRONTEND_API_URL}} \
          --from-literal=NEXT_PUBLIC_WS_SERVER=${{secrets.NEXT_PUBLIC_WS_SERVER}} \
          --namespace=default \
          --dry-run=client -o yaml

          kubectl create secret generic backend-secret \
          --from-literal=GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}} \
          --from-literal=GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}} \
          --from-literal=NEXT_PUBLIC_FRONTEND_API_URL=${{secrets.NEXT_PUBLIC_FRONTEND_API_URL}} \
          --from-literal=secret_key=${{secrets.SECRET_KEY}} \
          --from-literal=DATABASE_URL=${{secrets.DATABASE_URL}} \
          --from-literal=Redis_URL=${{secrets.REDIS_URL}} \
          --from-literal=password=${{secrets.REDIS_PASSWORD}} \
          --from-literal=port=${{secrets.REDIS_PORT}} \
          --namespace=default \
          --dry-run=client -o yaml

          kubectl create secret generic kafka-consumer-secret \
          --from-literal=DATABASE_URL=${{secrets.DATABASE_URL}} \
          --namespace=default \
          --dry-run=client -o yaml

          kubectl create secret generic ws-secret \
          --from-literal=DATABASE_URL=${{secrets.DATABASE_URL}} \
          --from-literal=Redis_URL=${{secrets.REDIS_URL}} \
          --from-literal=password=${{secrets.REDIS_PASSWORD}} \
          --from-literal=port=${{secrets.REDIS_PORT}} \
          --namespace=default \
          --dry-run=client -o yaml

          kubeseal --cert=pub-sealed-secrets.pem --format=yaml \
           < secret/docker-secret.yaml \
           > secret/docker-sealed-secret.yaml
           rm -rf secret/docker-secret.yaml

          kubeseal --cert=pub-sealed-secrets.pem --format=yaml \
          < secret/frontend-secret.yaml \
           > secret/frontend-sealed-secret.yaml
          rm -rf secret/frontend-secret.yaml


           kubeseal --cert=pub-sealed-secrets.pem --format=yaml \
           < secret/backend-secret.yaml \
           > secret/backend-sealed-secret.yaml
           rm -rf secret/backend-secret.yaml


          kubeseal --cert=pub-sealed-secrets.pem --format=yaml \
          < secret/kafka-consumer-secret.yaml \
          > secret/kafka-consumer-sealed-secret.yaml
          rm -rf secret/kafka-consumer-secret.yaml


          kubeseal --cert=pub-sealed-secrets.pem --format=yaml \
          < secret/ws-server-secret.yaml \
          > secret/ws-server-sealed-secret.yaml
          rm -rf secret/ws-server-secret.yaml

      - name: Commit and Push Changes
        run: |
          cd ~/gitops
          git config user.name "ci-bot"
          git config user.email "ci-bot@example.com"
          git add .
          git commit -m "Update images to SHA ${GITHUB_SHA}"
          git push
      
  
        
           
                  
    

      
